Add supportsInterface()
ERC725Alliance/erc725.js pull request #243
Opened 2022-10-04 16:02 UTC by fhildeb

### What kind of change does this PR introduce (bug fix, feature, docs update, ...)?

### What is the current behaviour (you can also link to an open issue here)?

### What is the new behaviour (if this is a feature change)?

### Other information:

2022-10-05 07:43 UTC, Hugoo requested changes

2022-10-05 07:43 UTC, Hugoo commented on src/lib/detector.test.ts
> +describe.only('supportsInterface', () => {
Please remove the only

2022-10-05 07:43 UTC, Hugoo commented on src/lib/detector.test.ts
> +        // eslint-disable-next-line no-new
Why ts-ignore?

2022-10-05 07:50 UTC, Hugoo commented on docs/classes/ERC725.md
> +##### 1. `interfaceIdOrName` - String of ID or name
```suggestion
##### 1. `interfaceIdOrName` - String
```

2022-10-05 07:50 UTC, Hugoo commented on docs/classes/ERC725.md
> +##### 2. `options` - Object of contract address and RPC URL
```suggestion
##### 2. `options` - Object
```

2022-10-05 15:04 UTC, Hugoo approved these changes

2022-10-06 08:10 UTC, fhildeb commented
Looks good, thanks!

2022-10-06 08:24 UTC, merged