fix: Filter out ALL_PERMISSIONS from keys in LSP6_DEFAULT_PERMISSIONS.
ERC725Alliance/erc725.js pull request #409
Opened 2024-04-04 20:33 UTC by richtera

### What kind of change does this PR introduce (bug fix, feature, docs update, ...)?

Filter out keys from LSP6_DEFAULT_PERMISSIONS because it now has ALL_PERMISSIONS.
Having ALL_PERMISSIONS set during encodePermissions will always return ALL_PERMISSIONS.
Currently calling decodePermissions will always return ALL_PERMISSIONS on.

### What is the current behaviour (you can also link to an open issue here)?

### What is the new behaviour (if this is a feature change)?

### Other information:

2024-04-05 15:58 UTC, CJ42 requested changes
can we remove biome from this PR, and put it in a separate PR please?
Otherwise the PR is really hard to review as there are too many changes and I can't filter out what is related to the permissions

2024-04-05 15:58 UTC, CJ42 commented on .vscode/settings.json
do we want to have these files?

2024-04-05 16:00 UTC, richtera reviewed
Since there are a lot of style changes here are the real changes.

2024-04-05 16:00 UTC, richtera commented on src/lib/permissions.ts
> +  let basePermissions = BigInt(0)
This is where the encodePermissions was changed.

2024-04-05 16:00 UTC, richtera commented on src/lib/permissions.ts
>      SIGN: false,
This is where the decodePermissions was changed.

2024-04-05 16:00 UTC, richtera commented on src/index.test.ts
> +      it('should decode ALL_PERMISSIONS', () => {
Here is the first new test

2024-04-05 16:00 UTC, richtera commented on src/index.test.ts
> +      it('should not decode CALL or ALL_PERMISSIONS if perms are missing', () => {
Here is the second new test

2024-04-06 16:01 UTC, richtera commented on .vscode/settings.json
Yes, these files are necessary to make sure any devs use the correct settings. It's kind of unfortunate but currently .editorconfig doesn't properly defined formatters and validators in a generic way. If this were to use a standard lsp https://microsoft.github.io/language-server-protocol/ then any editor could hook into it.

2024-04-06 16:01 UTC, richtera commented
I removed import sorting, so now only the cleanup and fixes are there.

2024-04-10 22:59 UTC, CJ42 requested changes
Added some review comments. Otherwise some nice cleanups here! 🙌

2024-04-10 22:59 UTC, CJ42 commented on package.json
> +  "version": "0.24.1-dev.5",
why `-dev.5`?

2024-04-10 22:59 UTC, CJ42 commented on package.json
> +    "format:fix": "prettier --write .",
nice addition 👌

2024-04-10 22:59 UTC, CJ42 commented on src/index.test.ts
> +        const permissions = { ALL_PERMISSIONS: true, CALL: false };
@skimaharvey was not the intended logic to be "all permissions except `CALL`" in this kind of case?

2024-04-10 22:59 UTC, CJ42 commented on src/index.test.ts
> +          false,
shouldn't this be `true`?

```suggestion
          true,
```

2024-04-10 22:59 UTC, CJ42 commented on src/index.test.ts
> +        const permissions = { ALL_PERMISSIONS: true };
how about a test like that:

```suggestion
        const permissions = { ALL_PERMISSIONS: true, SUPER_DELEGATECALL: true, DELEGATECALL: true };
```

Should lead to the same result right?

2024-04-10 22:59 UTC, CJ42 commented on src/lib/permissions.ts
> +  // Deal with ALL_PERMISSIONS the same way. So as long as all the bits in ALL_PERMISSIONS
I am very confused by this comment. I think might need a bit of re-writing and maybe a small example?

2024-04-11 08:31 UTC, CJ42 commented on src/index.test.ts
> +          'Re-reencoded permissions includes CALL',
isn't this error message incorrect?

```suggestion
          'Re-reencoded permissions does not include CALL',
```

2024-04-11 08:31 UTC, CJ42 commented on src/index.test.ts
> +        assert.strictEqual(
I guess we can also add a test for:

```js
        assert.strictEqual(
          redecodedPermissions.ALL_PERMISSIONS,
          true,
          'Re-reencoded permissions includes ALL_PERMISSIONS',
        );
```

2024-04-11 08:33 UTC, CJ42 commented on package.json
> +  "version": "0.24.1-dev.5",
will be overriten by release please, but let's remove it in case.

2024-04-11 08:34 UTC, CJ42 commented on src/index.test.ts
> +        const permissions = { ALL_PERMISSIONS: true, CALL: false };
yes that's the case. All good

2024-04-11 08:44 UTC, CJ42 approved these changes

2024-04-11 08:46 UTC, merged